version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm i
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
cache:
  paths:
    - '/root/.npm/**/*'
    - 'build/**/*'
